package com.taochong.joshuachang.mytextdemo.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.taochong.joshuachang.mytextdemo.db.Bean;
import com.taochong.joshuachang.mytextdemo.db.User;

import com.taochong.joshuachang.mytextdemo.db.BeanDao;
import com.taochong.joshuachang.mytextdemo.db.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig beanDaoConfig;
    private final DaoConfig userDaoConfig;

    private final BeanDao beanDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        beanDaoConfig = daoConfigMap.get(BeanDao.class).clone();
        beanDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        beanDao = new BeanDao(beanDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Bean.class, beanDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        beanDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public BeanDao getBeanDao() {
        return beanDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
